"""Added Investable base model and updated CharityProject and Donation models

Revision ID: 2324a330730a
Revises: cd5d2c51efe7
Create Date: 2024-03-28 18:47:44.884537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2324a330730a'
down_revision = 'cd5d2c51efe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charityproject')
    op.drop_table('donation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('full_amount', sa.INTEGER(), nullable=False),
    sa.Column('invested_amount', sa.INTEGER(), nullable=True),
    sa.Column('fully_invested', sa.BOOLEAN(), nullable=True),
    sa.Column('create_date', sa.DATETIME(), nullable=True),
    sa.Column('close_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charityproject',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('full_amount', sa.INTEGER(), nullable=False),
    sa.Column('invested_amount', sa.INTEGER(), nullable=True),
    sa.Column('fully_invested', sa.BOOLEAN(), nullable=True),
    sa.Column('create_date', sa.DATETIME(), nullable=True),
    sa.Column('close_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
